# Generated by Django 3.2.23 on 2023-11-16 08:34

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер бокса')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('length', models.FloatField(verbose_name='Длина')),
                ('width', models.FloatField(verbose_name='Ширина')),
                ('height', models.FloatField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Мобильный номер')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('height', models.FloatField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_rent_date', models.DateTimeField(db_index=True, verbose_name='Дата начала аренды')),
                ('end_rent_date', models.DateTimeField(db_index=True, verbose_name='Дата окончания аренды')),
                ('warehouse_delivery', models.BooleanField(default=False, verbose_name='Доставка на склад')),
                ('from_warehouse_delivery', models.BooleanField(default=False, verbose_name='Доставка со склада')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='renta_warehouse.box', verbose_name='Бокс на складе')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='renta_warehouse.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
