# Generated by Django 3.2.23 on 2023-11-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta_warehouse', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='number',
            field=models.IntegerField(verbose_name='Номер бокса'),
        ),
    ]
