# Generated by Django 3.2.23 on 2023-11-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta_warehouse', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='actual_end_rent_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Фактическая дата окончания аренды'),
        ),
    ]
