# Generated by Django 3.2.23 on 2023-11-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta_warehouse', '0003_alter_order_actual_end_rent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='free',
            field=models.BooleanField(default=True, verbose_name='Свободный бокс'),
        ),
    ]
